### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Rufis01** [Rufis01/CHIP8_Emu#1]
So far the emulator works with no bugs, but it lacks of some features:
- [x] ~Make a separate thread for audio (should run @60 Hz, which is too slow for the interpreter)~
      Apparently using threads is bad, so just time everything correctly
- [x] Speed up the interpreter
- [x] Add a menubar
  - [x] Add the abilty to load roms
  - [ ] Add an option to change speed
  - [ ] Add an option to change controls
  - [ ] CUSTOMIZATION!
- [ ] Implement RCA 1802 emulation

Debug:
- [ ] Memory viewer
- [ ] Disassembler

Optimization:
- [ ] Get rid of Thread.sleep() to time events
- [ ] Clean up the code

Other:
- [ ] Make a function to generate the beep, witouth playing an audio file
- [ ] Multiplayer
